name: Decide which clusters/hubs to run helm upgrade for and create matrix jobs

on:
  push:
    branches:
      - main
    paths:
      - "**.values.yaml"
      - "**cluster.yaml"
      - "helm-charts/basehub/**"
      - "helm-charts/daskhub/**"
      - "helm-charts/support/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "**.values.yaml"
      - "**cluster.yaml"
      - "helm-charts/basehub/**"
      - "helm-charts/daskhub/**"
      - "helm-charts/support/**"
      - ".github/workflows/**"

jobs:
  filepaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml rich

      - uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run python script
        run: |
          python helm_upgrade_decision_logic.py "${{ steps.changed-files.outputs.added_modified }}"

      - name: Echo hub matrix jobs
        run: |
          echo ${{ toJson(env.HUB_MATRIX_JOBS) }}

      - name: Echo support matrix jobs
        run: |
          echo ${{ toJson(env.SUPPORT_MATRIX_JOBS) }}

      - name: Run python script with pretty-print
        run: |
          # I know, I'm writing the worst Python ever here. I'm just fudging things to get all the workflows running.
          python -m mymodule.helm_upgrade_decision_logic "${{ steps.changed-files.outputs.added_modified }}" --pretty-print
