on: [workflow_dispatch]

jobs:
  test-includes-matrix-with-list:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { food: ice-cream, flavour: chocolate }
          - { food: ice-cream, flavour: vanilla }
          - { food: ice-cream, flavour: strawberry }
          - { food: pizza, flavour: pepperoni }
          - { food: pizza, flavour: margarita }
          - { food: pizza, flavour: hawaiian }
    steps:
      - env:
          FOOD: ${{ matrix.food }}
          FLAVOUR: ${{ matrix.flavour }}
        run: |
          echo "My favourite food is ${FOOD}. I like ${FLAVOUR} the best!"
