name: Parsing filepaths to Python

on:
  push:
    branches:
      - main
    paths:
      - "**.values.yaml"
      - "**cluster.yaml"
      - "helm-charts/basehub/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "**.values.yaml"
      - "**cluster.yaml"
      - "helm-charts/basehub/**"
      - ".github/workflows/**"

jobs:
  filepaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: run python script
        run: |
          python src/input-from-actions.py "${{ steps.changed-files.outputs.added_modified }}"

      - name: hub matrix jobs
        run: |
          echo ${{ toJson(env.HUB_MATRIX_JOBS) }}

      - name: support matrix jobs
        run: |
          echo ${{ toJson(env.SUPPORT_MATRIX_JOBS) }}

      - name: run python script with pretty-print
        run: |
          python src/input-from-actions.py "${{ steps.changed-files.outputs.added_modified }}" --pretty-print
