name: Setting env vars from Python

on: [workflow_dispatch]

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: action/setup-python@master
        with:
          python-version: "3.10"
      - run: |
          python src/setting-env-vars.py
      - run: |
          echo ${{ env }}
          echo ${{ env.TEST }}
