name: Run the deployer's tests

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "tests/**"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - "tests/**"

jobs:
  test-deployer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install ruamel.yaml rich pytest pytest-env
      - name: Run tests
        run: |
          python -m pytest -vvv --color=yes
